import fs from 'node:fs'
import { chromium } from 'playwright-core'

const credentials = Object.fromEntries(fs.readFileSync('.secrets/admin-login','utf8').trim().split('\n').map(line => line.split('=')))
const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
const errors = []
page.on('pageerror', error => errors.push(error.message))
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
await page.goto(process.env.STOCK_DESK_URL ?? 'http://127.0.0.1:5187/', { waitUntil: 'networkidle' })
await page.screenshot({ path: '/tmp/stock-login.png', fullPage: true })
await page.getByPlaceholder('you@business.com').fill(credentials.email)
await page.getByPlaceholder('Your password').fill(credentials.password)
await page.getByRole('button', { name: 'Sign in' }).click()
await page.locator('.page-heading h1').waitFor({ timeout: 30000 })
await page.screenshot({ path: '/tmp/stock-dashboard.png', fullPage: true })
await page.getByRole('button', { name: 'Inventory', exact: true }).click()
await page.locator('.page-heading h1').getByText('Inventory').waitFor()
await page.screenshot({ path: '/tmp/stock-inventory.png', fullPage: true })
await page.getByRole('button', { name: 'Reports', exact: true }).click()
await page.getByRole('button', { name: 'Stock balance & valuation' }).click()
await page.locator('.loading-line').waitFor({ state: 'hidden' })
if (await page.locator('.form-error').count()) throw new Error(await page.locator('.form-error').innerText())
await page.screenshot({ path: '/tmp/stock-reports.png', fullPage: true })
await page.getByRole('button', { name: 'Point of sale' }).click()
await page.locator('.page-heading h1').getByText('Point of sale').waitFor()
await page.screenshot({ path: '/tmp/stock-pos.png', fullPage: true })
await page.setViewportSize({ width: 390, height: 844 })
await page.screenshot({ path: '/tmp/stock-pos-mobile.png', fullPage: true })
const mobileOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
console.log(JSON.stringify({ headings: await page.locator('.page-heading h1').allTextContents(), errors, mobileOverflow, screenshots: ['/tmp/stock-login.png','/tmp/stock-dashboard.png','/tmp/stock-inventory.png','/tmp/stock-reports.png','/tmp/stock-pos.png','/tmp/stock-pos-mobile.png'] }))
await browser.close()
